version: '3.7'

services:

  task-tracker:
    container_name: task-tracker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/task-tracker-front'
      - '/task-tracker-front/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true